### ISSUE TITLE
Error on TFS 2015 Aggregator

### ISSUE THREAD

**Issue by marsyhc** [tfsaggregator/tfsaggregator#148]
Hi,

I encountered an issue on 2.1.178.0, please see the detail below, and the rule file is attached.
[TFSAggregator2.ServerPlugin.policies.zip](https://github.com/tfsaggregator/tfsaggregator/files/312129/TFSAggregator2.ServerPlugin.policies.zip)
Would be very much appreciated if anyone can help.

Log Name:      Application
Source:        TFSAggregator
Date:          6/13/2016 10:57:12 PM
Event ID:      47513
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      SHAAPPD01102.devint.ad.insidemedia.net
Description:
Exception encountered processing notification: Object reference not set to an instance of an object. 
Stack Trace:   at RESERVED.Script_RollupStoryPoints.RunScript(IWorkItemExposed self, IWorkItemRepositoryExposed store, IRuleLogger logger) in c:\Users\SHATFSService.Servic\AppData\Local\Temp\dir5v3xn.0.cs:line 26
   at Aggregator.Core.Script.DotNetScriptEngine`1.RunScript(Assembly assembly, String scriptName, IWorkItem self, IWorkItemRepository store) in C:\projects\tfsaggregator\Aggregator.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 159
   at Aggregator.Core.Script.DotNetScriptEngine`1.Run(String scriptName, IWorkItem workItem, IWorkItemRepository store) in C:\projects\tfsaggregator\Aggregator.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 212
   at Aggregator.Core.EventProcessor.ApplyRules(IWorkItem workItem, IEnumerable`1 rules) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 92
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 63
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 87
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="TFSAggregator" />
    <EventID Qualifiers="0">47513</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-06-13T14:57:12.000000000Z" />
    <EventRecordID>4413604</EventRecordID>
    <Channel>Application</Channel>
    <Computer>SHAAPPD01102.devint.ad.insidemedia.net</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Exception encountered processing notification: Object reference not set to an instance of an object. 
Stack Trace:   at RESERVED.Script_RollupStoryPoints.RunScript(IWorkItemExposed self, IWorkItemRepositoryExposed store, IRuleLogger logger) in c:\Users\SHATFSService.Servic\AppData\Local\Temp\dir5v3xn.0.cs:line 26
   at Aggregator.Core.Script.DotNetScriptEngine`1.RunScript(Assembly assembly, String scriptName, IWorkItem self, IWorkItemRepository store) in C:\projects\tfsaggregator\Aggregator.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 159
   at Aggregator.Core.Script.DotNetScriptEngine`1.Run(String scriptName, IWorkItem workItem, IWorkItemRepository store) in C:\projects\tfsaggregator\Aggregator.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 212
   at Aggregator.Core.EventProcessor.ApplyRules(IWorkItem workItem, IEnumerable`1 rules) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 92
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 63
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32&amp; statusCode, String&amp; statusMessage, ExceptionPropertyCollection&amp; properties) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 87</Data>
  </EventData>
</Event>

**Comment by giuliov** [comment]
There is not much to work on, except the `Temp\dir5v3xn.0.cs:line 26` snipped. It says that the exception is thrown on line 26 of the generated file, which points to line 10 of the first rule (_RollupStoryPoints_) i.e. the expression

    (double)self.Parent["Microsoft.VSTS.Scheduling.StoryPoints"] + (double)child["Microsoft.VSTS.Scheduling.StoryPoints"];

In general you cannot assume that a value is there and use a cast, see the [Null](https://github.com/tfsaggregator/tfsaggregator/wiki/Scripting-Pitfalls) section.

**Comment by marsyhc** [comment]
Thank you @giuliov, it is working now.
