### ISSUE TITLE
Not working on TFS Update2

### ISSUE THREAD

**Issue by Russweb** [tfsaggregator/tfsaggregator#151]
Installed on the app server.
Did just a basic rollup policy of hours on tasks to user stories.
Used examples from documentation.
Tried the console app. Works just fine.
Applied policy to the server policy file. **Eventlog shows a no go**.
Says I don't have permissions to access the work item or it doesnt exist.
It definitely exists. Changing it is what triggered TFSAggregator.
So tha leaves permissions or another bug.
How would I possibly not have permissions to access it if I am the one that edited it?
Is it indicating that somehow we have to run something with impersonation?
**Policy file attached.**

[TFSAggregator2.ServerPlugin.policies.txt](https://github.com/tfsaggregator/tfsaggregator/files/338241/TFSAggregator2.ServerPlugin.policies.txt)

The description for Event ID 47513 from source TFSAggregator cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Exception encountered processing notification: TF26198: The work item does not exist, or you do not have permission to access it. 
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.LoadWorkItemFromRowSetInternal(Int32 rev, Nullable`1 asof, IWorkItemRowSets witem)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem..ctor(WorkItemStore store, Int32 id)
   at Aggregator.Core.Facade.WorkItemRepository.GetWorkItem(Int32 workItemId) in C:\projects\tfsaggregator\Aggregator.Core\Facade\WorkItemRepository.cs:line 50
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 58
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84

the message resource is present but the message is not found in the string/message table

**Comment by Russweb** [comment]
Ok...so I just answered my own question, but it still seems a bit silly to me.
I had to add the service account that runs TFS services to either the collection or project in order for it to have permissions to update a work item.
Seems it should have this to start with since it runs the whole system.

**Comment by giuliov** [comment]
Good you resolved it. I think we have to explain this better in the docs, so I queue Issue #152 to track it.
