### ISSUE TITLE
The value for the field 'Board Lane' cannot be changed.

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#191]
[Critical]    13.613 Exception encountered processing notification: TF26194: The value for the field 'Board Lane' cannot be changed.
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.SetFieldValueExternal(FieldDefinition fd, Object value)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Microsoft.TeamFoundation.WorkItemTracking.Client.IRevisionInternal.SetFieldValue(FieldDefinition fd,
Object value)
   at Aggregator.Core.Facade.FieldWrapper.set_Value(Object value) in C:\projects\tfsaggregator\Aggregator.Core\Facade\FieldWrapper.cs:line 44
   at Aggregator.Core.Extensions.DoubleFixFieldDecorator.set_Value(Object value) in C:\projects\tfsaggregator\Aggregator.Core\Extensions\DoubleFixFieldDecorator.cs:l
ine 61
   at Aggregator.Core.Facade.WorkItemWrapper.set_Item(String name, Object value) in C:\projects\tfsaggregator\Aggregator.Core\Facade\WorkItemWrapper.cs:line 81
   at RESERVED.Script_AutoUpdateAreaPathForBusinessProjects.RunScript(IWorkItemExposed self, IWorkItemRepositoryExposed store, IRuleLogger logger)
   at Aggregator.Core.Script.DotNetScriptEngine`1.RunScript(Assembly assembly, String scriptName, IWorkItem self, IWorkItemRepository store) in C:\projects\tfsaggreg
ator\Aggregator.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 152
   at Aggregator.Core.Script.DotNetScriptEngine`1.Run(String scriptName, IWorkItem workItem, IWorkItemRepository store) in C:\projects\tfsaggregator\Aggregator.Core\
Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 212
   at Aggregator.Core.EventProcessor.ApplyRule(Rule rule, IWorkItem workItem) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 109
   at Aggregator.Core.EventProcessor.ApplyRules(IWorkItem workItem, IEnumerable`1 rules) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 95
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in C:\projects\tfsaggregator\Aggregator.Core\EventProce
ssor.cs:line 62
   at Aggregator.ConsoleApp.RunCommand.Run(String[] remainingArguments) in C:\projects\tfsaggregator\Aggregator.ConsoleApp\RunCommand.cs:line 116

**Comment by jessehouwing** [comment]
As the exception says, you can't change the board lane or kanban column
from a rule.

When we process we do not know which team was selected, and without the
team context we can't set the board column or swimlanes.
