### ISSUE TITLE
Sendmail works only once after restart TFS.

### ISSUE THREAD

**Issue by p13x** [tfsaggregator/tfsaggregator#206]
Hi,
First lunch work without a problem. 
After that I get a message:

```
[3136]    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in C:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84 
[3136] TFSAggregator: [Critical]    Exception encountered processing notification: Object reference not set to an instance of an object. 
[3136]    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in C:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84 
```

I'm using TFS 2017 RTM and TFSAggregator 2.2.0.

Any clue how to fix that?

**Comment by giuliov** [comment]
No, I need to drill down.
Can you share more details (log and rule), maybe via email?

**Comment by p13x** [comment]
The rule I copied from your documentation. Just want to test.
Of course, I used proper email address ;) I have SMTP server configured in TFS.
```
string to = "test@example.com";
string subject = "Sent from a Rule";
string body = "It worked!";
Library.SendMail(to, subject, body);

```
About log. I found something like this.
```
Exception encountered processing notification: Object reference not set to an instance of an object. 
Stack Trace:   at Microsoft.TeamFoundation.Framework.Server.VssRequestContext.TimeRequest.RecordTraceEnterTiming(String area, String layer, String methodName)
   at Microsoft.TeamFoundation.Framework.Server.TeamFoundationMailService.LoadSettings(IVssRequestContext requestContext)
   at Aggregator.Core.Facade.ScriptLibrary.SendMail(String to, String subject, String body) in C:\a\1\s\Aggregator.Core\Facade\ScriptLibrary.cs:line 29
   at RESERVED.Script_sendEmail.RunScript(IWorkItemExposed self, IWorkItemRepositoryExposed store, IRuleLogger logger, IScriptLibrary Library) in c:\Users\username\AppData\Local\Temp\xi10zzeb.18.cs:line 23
   at Aggregator.Core.Script.DotNetScriptEngine`1.RunScript(Assembly assembly, String scriptName, IWorkItem self, IWorkItemRepository store) in C:\a\1\s\Aggregator.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 150
   at Aggregator.Core.Script.DotNetScriptEngine`1.Run(String scriptName, IWorkItem workItem, IWorkItemRepository store) in C:\a\1\s\Aggregator.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 243
   at Aggregator.Core.EventProcessor.ApplyRule(Rule rule, IWorkItem workItem) in C:\a\1\s\Aggregator.Core\EventProcessor.cs:line 109
   at Aggregator.Core.EventProcessor.ApplyRules(IWorkItem workItem, IEnumerable`1 rules) in C:\a\1\s\Aggregator.Core\EventProcessor.cs:line 95
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in C:\a\1\s\Aggregator.Core\EventProcessor.cs:line 62
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32&amp; statusCode, String&amp; statusMessage, ExceptionPropertyCollection&amp; properties) in C:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84
```

**Comment by giuliov** [comment]
This stack trace tells everything: TFS Aggregator queries TFS for mail configuration and this latter fails.

Please check that your TFS has enabled email alerts as described [here](https://www.visualstudio.com/en-us/docs/setup-admin/tfs/admin/setup-customize-alerts) and they works using the test link.

**Comment by giuliov** [comment]
@p13x I have been able to reproduce the exception in 2015.3 and 2017.0. It will take more time to find a solution.

**Comment by giuliov** [comment]
I have a solution but want to check with MS people which is the best way to go.

**Comment by p13x** [comment]
Great.

**Comment by p13x** [comment]
This feature works fine on TFS 2017 update 2 with TFSAggregator 2.3.0 RC1.
