### ISSUE TITLE
TFS 2017 Update 2 RC1 - don't work rollups.

### ISSUE THREAD

**Issue by p13x** [tfsaggregator/tfsaggregator#234]
Hi,
Looks like in new TFS tfsaggregator don't work:

[3396] TFSAggregator: [Critical]    Exception encountered processing notification: Method not found: 'Void Microsoft.TeamFoundation.Integration.Server.ICommonStructureService.GetProjectProperties(Microsoft.TeamFoundation.Framework.Server.IVssRequestContext, System.String, System.String ByRef, System.String ByRef, Microsoft.TeamFoundation.Integration.Server.CommonStructureProjectProperty[] ByRef)'. 

Can you verify that?

**Comment by jessehouwing** [comment]
Looks like a broken api again. Argh.

**Comment by giuliov** [comment]
I did a quick test and seems to work: can you share more details?

**Comment by p13x** [comment]
In event viewer I found:

Exception encountered processing notification: Method not found: 'Void Microsoft.TeamFoundation.Integration.Server.ICommonStructureService.GetProjectProperties(Microsoft.TeamFoundation.Framework.Server.IVssRequestContext, System.String, System.String ByRef, System.String ByRef, Microsoft.TeamFoundation.Integration.Server.CommonStructureProjectProperty[] ByRef)'. 
Stack Trace:   at Aggregator.Core.Facade.RequestContextWrapper.GetProjectProperties(Uri projectUri)
   at Aggregator.Core.Configuration.TemplateScope.GetTemplateInfo(IRequestContext currentRequestContext, INotification currentNotification) in D:\a\1\s\Aggregator.Core\Configuration\TemplateScope.cs:line 55
   at Aggregator.Core.Configuration.TemplateScope.Matches(IRequestContext currentRequestContext, INotification currentNotification) in D:\a\1\s\Aggregator.Core\Configuration\TemplateScope.cs:line 39
   at Aggregator.Core.EventProcessor.<>c__DisplayClass7_0.<FilterPolicies>b__1(PolicyScope scope) in D:\a\1\s\Aggregator.Core\EventProcessor.cs:line 84
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in D:\a\1\s\Aggregator.Core\EventProcessor.cs:line 54
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84

**Comment by giuliov** [comment]
Hmm it could be something specific to the Template filter. IIRC @jessehouwing deprecated it.
Can you add some context info: which TFS version you run, which Aggregator version, what changed in the system (e.g. upgrade), etc.

**Comment by jessehouwing** [comment]
The api for this area has changed a couple of times and I expect that this
is due to the I troduction of the new inherited procestemplate model and
surrounding work the product team is doing.

Probably the simplest way to check would be to recompile against the very
latest server binaries and it looks like we'll have to add yet another
compiler condition. Argh.

The template filter is not deprecated, but the version number of it and a
few other properties were removed.

**Comment by jessehouwing** [comment]
Looks like this should fix it:

```
        public IProjectProperty[] GetProjectProperties(Uri projectUri)
        {
            var ics = this.context.GetService<ICommonStructureService>();
            string projectName;
            string projectState;

#if TFS2017u2
            CommonStructureProjectProperty[] projectProperties;
            ics.GetProjectProperties(this.context, projectUri.ToString(), out projectName, out projectState, out projectProperties);
#else
            var info = ics.GetProject(this.context, projectUri.ToString()).ToProjectInfo();
            var projectProperties = info.Properties;
#endif

            return projectProperties.Select(p => (IProjectProperty)new ProjectPropertyWrapper() { Name = p.Name, Value = p.Value }).ToArray();
        }
```

**Comment by jessehouwing** [comment]
Just pushed a branch with the required changes. Needs new TFS server binaries on the build server and adds another project configuration (-2017.2).I've also updated most of the installer code, but I don't have the TFS 2017 RTM and TFS 2017u1 build numbers at hand to correctly configure the Product.wxs.

**Comment by jessehouwing** [comment]
See: https://github.com/tfsaggregator/tfsaggregator/tree/features/tfs2017u2

**Comment by p13x** [comment]
I've used a new branch.
Console App works.
In server plugin I get messages:
```
[4308] TFSAggregator: [Verbose]     Building Script Engine for C# 
[4308] TFSAggregator: [Information] Starting processing on workitem #64477 
[4308] TFSAggregator: [Diagnostic]  Policy scope Collections(DefaultCollection) matches DefaultCollection 
[4308] TFSAggregator: [Diagnostic]  Policy scope ProcessTemplate(CMMI) does not match  
[4308] TFSAggregator: [Verbose]     No polices apply 
[4308] TFSAggregator: [Information] Processing completed: No operation 

```
But If I comment:
`<!-- <templateScope name="CMMI" /> -->`

Then server plugin works fine.

Can you verify?

**Comment by jessehouwing** [comment]
Similar remark from slack. I don't have time to investigate at the moment,
I'm guessing the template properties are not being returned, have been
renamed or are otherwise not what we were expecting.

**Comment by RangerDjanger** [comment]
Just wondering if there any update on the fix for 2017 Update 2 RC1 compatibility?

**Comment by giuliov** [comment]
@jessehouwing released the patches on **features/tfs2017u2**.
I have to integrate the changes with the build in VSTS.

**Comment by jessehouwing** [comment]
They make either compile again, but the process template filter (filter by
name of process template) no longer works. Haven't had time (and won't have
time) to debug any time soon.

**Comment by RangerDjanger** [comment]
Thanks @giuliov , @jessehouwing . I've got the patch branch. If I have time myself I'll have a crack at debugging the template filter issue.

**Comment by dasMulli** [comment]
fyi TFS 2017 update 2 was released yesterday. didn't (yet) give the patches a try but is there an ETA for a possible release including a fix? (days/weeks/months?)

**Comment by giuliov** [comment]
@dasMulli working on it.
I collected all sparse work into develop branches of the three repos, testing now.
Crossing fingers, the release should be ready by next week.

**Comment by jessehouwing** [comment]
@giuliov were you able to test the templatescope? Or is it now broken.

**Comment by giuliov** [comment]
I hadn't test it yet

**Comment by jessehouwing** [comment]
Then that's probably still a known issue.
