### ISSUE TITLE
shall "NT AUTHORITY/NETWORK SERVICES" be added to "Project Collection Administrators" group even if I'm using autoImpersonate to true?

### ISSUE THREAD

**Issue by francesco-sclano** [tfsaggregator/tfsaggregator#238]
Hi,
in order to properly use TFS Aggregator with:
- TFS 2017 update 1 on premises installed on windows server 2012 r2
- and the setting explained here https://github.com/tfsaggregator/tfsaggregator/issues/236

Have I also to add "NT AUTHORITY/NETWORK SERVICES" as member of "Project Collection Administrators" group for every Project Collection?

Otherwise it seems that I'll get this error. Do you please confirm?
Exception encountered processing notification: TF30063: You are not authorized to access http://XXXXXXXXXXXXXX:8080/tfs/YYYYYYYYYYYYYYY. 
Stack Trace:   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.EnsureTokenProvider(HttpWebResponse webResponse)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequest()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpRequestChannel.Request(TfsMessage message, TimeSpan timeout)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.Invoke(TfsClientOperation operation, Object[] parameters, TimeSpan timeout, Object[]& outputs)
   at Microsoft.TeamFoundation.Framework.Client.IdentityManagementWebService.ReadIdentitiesById(Guid[] teamFoundationIds, Int32 queryMembership, Int32 features, Int32 options, IEnumerable`1 propertyNameFilters, Int32 propertyScope)
   at Microsoft.TeamFoundation.Framework.Client.IdentityManagementService.ReadIdentities(Guid[] teamFoundationIds, MembershipQuery queryMembership)
   at Aggregator.Core.Facade.RequestContextWrapper.GetIdentityToImpersonate(Uri projectCollectionUrl) in D:\a\1\s\Aggregator.Core\Facade\RequestContextWrapper.cs:line 96
   at Aggregator.Core.Context.RuntimeContext.GetConnectionInfo() in D:\a\1\s\Aggregator.Core\Context\RuntimeContext.cs:line 205
   at Aggregator.Core.Facade.WorkItemRepository..ctor(IRuntimeContext context) in D:\a\1\s\Aggregator.Core\Facade\WorkItemRepository.cs:line 41
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(IRuntimeContext runtimeContext) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 67
   at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in D:\a\1\s\Aggregator.Core\Context\RuntimeContext.cs:line 219
   at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in D:\a\1\s\Aggregator.Core\Context\RuntimeContext.cs:line 233
   at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in D:\a\1\s\Aggregator.Core\EventProcessor.cs:line 40
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84

**Comment by deka** [comment]
Is "NT AUTHORITY/NETWORK SERVICES" the TFS service account ? You can check by opening the TFS administrator console and click on "Application Tiers"

**Comment by jessehouwing** [comment]
Yes, it needs to connect to then do an "act on behalf of".
