### ISSUE TITLE
Issue on querying WIs

### ISSUE THREAD

**Issue by manne** [tfsaggregator/tfsaggregator#246]
Hello,

I developed rules on a staging TFS for TFS aggregator. After the rules worked as wanted, the rules have been deployed on the production TFS.
On the production system TFS Aggregator throws following exception, seen in the event viewer:
```
Exception encountered processing notification: Error HRESULT E_FAIL has been returned from a call to a COM component. 
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.DataStoreNative64.BeginDataStoreInit(IntPtr handle, String defaultCachePath, String instanceId, Int32 cacheVersion)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.Datastore.BeginDataStoreInit(String defaultCachePath, String instanceId, Int32 cacheVersion)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.InitializeInternal()
   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollection.InitializeTeamFoundationObject(String fullName, Object instance)
   at Microsoft.TeamFoundation.Client.TfsConnection.CreateServiceInstance(Assembly assembly, String fullName)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService(Type serviceType)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService[T]()
   at Aggregator.Core.Facade.WorkItemRepository..ctor(IRuntimeContext context) in D:\a\1\s\Aggregator.Core\Facade\WorkItemRepository.cs:line 44
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(IRuntimeContext runtimeContext) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 67
   at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in D:\a\1\s\Aggregator.Core\Context\RuntimeContext.cs:line 219
   at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in D:\a\1\s\Aggregator.Core\Context\RuntimeContext.cs:line 233
   at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in D:\a\1\s\Aggregator.Core\EventProcessor.cs:line 40
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84
```

Following actions I made to isolate the cause (every action is done of the first production application tier):
- Used Procmon to analyze if TFS can find the Microsoft.WitDataStore64.dll
  - Yes, it gets found
- Used DependencyWalker if a transient dependency of Microsoft.WitDataStore64.dll is missing
  - Every transient dependency is available
- Implemented an ASP.NET website which retrieves a single work item
  - Copied the dependent DLLs from the first production app tier
  - Deployed on the first production app tier in the application pool "Microsoft Team Foundation Server Application Pool"
   - Result: each call is returning the correct title of the workitem with the id 363
     - http://localhost:8090/api/values/1
     - http://FQDN:8090/api/values/1
     - http://localhost:8090/api/values/0
     - http://FQDN:8090/api/values/0
  - Code (FQDN is a placeholder for the actual FQDN of the production TFS instance)
```CSharp
public class ValuesController : ApiController
{
	// GET api/values/5
	public string Get(int id)
	{
		var target = id == 0 ? new Uri("http://localhost:8080/tfs/DefaultCollection") : new Uri("http://FQDN:8080/tfs/DefaultCollection");

		using (var collection = new TfsTeamProjectCollection(target))
		{
			collection.EnsureAuthenticated();
			var workItemStore = collection.GetService<WorkItemStore>();
			var workItem = workItemStore.GetWorkItem(363);
			return workItem.Title;
		}
	}
}
```
- Activated tracing in TFS for more information
  - Result
```
[, PID 5460, TID 7464, 2017/08/25 10:31:06.279] # Team Foundation Trace for component  started at 08/25/2017 10:31:06 [note all date/time values are in UTC].

[, PID 5460, TID 7464, 2017/08/25 10:31:06.279] # Trace listener: Microsoft.TeamFoundation.TeamFoundationTextWriterTraceListener

[, PID 5460, TID 7464, 2017/08/25 10:31:06.279] # Config settings: Assert UI Enabled=True Launch Debugger=True ASP.NET=True

[, PID 5460, TID 7464, 2017/08/25 10:31:09.248] w3wp.exe Information: 0 : Updated Trace Settings

[, PID 5460, TID 7464, 2017/08/25 10:31:09.248] w3wp.exe Information: 0 : Initialized the Trace Configurations

[, PID 5460, TID 7464, 2017/08/25 10:31:09.523] Registering Tagging routes

[, PID 5460, TID 6304, 2017/08/25 10:31:15.226] TFSAggregator: [Information] Aggregator.Core started, version: 2.2.1+Branch.master.Sha.5fd14faab06a1f011d4c09ec108de8bfc54bde57, build: 2.2.1.0, configuration: Release [TFS 2015.2]

[, PID 5460, TID 6304, 2017/08/25 10:31:15.273] TFSAggregator: [Information] Configuration loaded successfully from 'C:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.policies'

[, PID 5460, TID 6304, 2017/08/25 10:31:15.273] TFSAggregator: [Verbose]     Connecting to http://FQDN:8080/tfs/DefaultCollection/ as tfsserviceprod

[, PID 5460, TID 6304, 2017/08/25 10:31:15.813] TFSAggregator: [Critical]    Exception encountered processing notification: Error HRESULT E_FAIL has been returned from a call to a COM component. 
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.DataStoreNative64.BeginDataStoreInit(IntPtr handle, String defaultCachePath, String instanceId, Int32 cacheVersion)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.Datastore.BeginDataStoreInit(String defaultCachePath, String instanceId, Int32 cacheVersion)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.InitializeInternal()
   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollection.InitializeTeamFoundationObject(String fullName, Object instance)
   at Microsoft.TeamFoundation.Client.TfsConnection.CreateServiceInstance(Assembly assembly, String fullName)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService(Type serviceType)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService[T]()
   at Aggregator.Core.Facade.WorkItemRepository..ctor(IRuntimeContext context) in D:\a\1\s\Aggregator.Core\Facade\WorkItemRepository.cs:line 44
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(IRuntimeContext runtimeContext) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 67
   at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in D:\a\1\s\Aggregator.Core\Context\RuntimeContext.cs:line 219
   at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in D:\a\1\s\Aggregator.Core\Context\RuntimeContext.cs:line 233
   at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in D:\a\1\s\Aggregator.Core\EventProcessor.cs:line 40
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84
```

# Question
How can TFS Aggregator be run on the production TFS?
If further information is wanted and/or needed, I am happy to provide it.

# Environment
## First Instance (Production)
- Two application tiers behind one NLB
- Service account (tfsserviceprod)
  - Is local administrator
  - Domain account
- Data Tier on a separate VM

## Second Instance (Staging)
- One application tier
- Service account (tfsservicetest)
  - Is local administrator
  - Domain account
- Data Tier on the same VM

### TFS/TFS Aggregator versions
TFS Aggregator -  2.2.1
TFS 2015 Update 3 - 14.102.25423.0

### Installed software
- On both instances (on production TFS: both application tiers) are almost the same software installed
  - The staging VM has got following additional software installed
    - Sonatype Nexus 3.0.1-01
    - Sonatype Nexus 3.0.2-02
    - SQL Server 2012

**Comment by giuliov** [comment]
I do not remember a similar issue and `E_FAIL` can mean anything.
It is clear that something is happening while the TFS Client OM, used by Aggregator, tries to connect to the server.
You may try adding the [`server` element](https://tfsaggregator.github.io/using/policy-syntax/#runtime-section), e.g. `<server baseUrl="http://localhost:8080/tfs" />`, to force a local connection and see if this is related in some way.

**Comment by manne** [comment]
thank you very much for the quick response.
After adding the configuration, there is still the same exception
```
[, PID 8452, TID 6696, 2017/08/28 17:05:34.018] # Team Foundation Trace for component  started at 08/28/2017 17:05:34 [note all date/time values are in UTC].

[, PID 8452, TID 6696, 2017/08/28 17:05:34.018] # Trace listener: Microsoft.TeamFoundation.TeamFoundationTextWriterTraceListener

[, PID 8452, TID 6696, 2017/08/28 17:05:34.018] # Config settings: Assert UI Enabled=True Launch Debugger=True ASP.NET=True

[, PID 8452, TID 6696, 2017/08/28 17:05:37.768] w3wp.exe Information: 0 : Updated Trace Settings

[, PID 8452, TID 6696, 2017/08/28 17:05:37.768] w3wp.exe Information: 0 : Initialized the Trace Configurations

[, PID 8452, TID 6696, 2017/08/28 17:05:38.049] Registering Tagging routes

[, PID 6636, TID 5224, 2017/08/28 17:05:41.801] # Team Foundation Trace for component  started at 08/28/2017 17:05:41 [note all date/time values are in UTC].

[, PID 6636, TID 5224, 2017/08/28 17:05:41.801] # Trace listener: Microsoft.TeamFoundation.TeamFoundationTextWriterTraceListener

[, PID 6636, TID 5224, 2017/08/28 17:05:41.801] # Config settings: Assert UI Enabled=True Launch Debugger=True ASP.NET=True

[, PID 6636, TID 5224, 2017/08/28 17:05:44.457] w3wp.exe Information: 0 : Updated Trace Settings

[, PID 6636, TID 5224, 2017/08/28 17:05:44.457] w3wp.exe Information: 0 : Initialized the Trace Configurations

[, PID 6636, TID 5224, 2017/08/28 17:05:44.801] Registering Tagging routes

[, PID 6636, TID 7692, 2017/08/28 17:05:50.390] TFSAggregator: [Information] Aggregator.Core started, version: 2.2.1+Branch.master.Sha.5fd14faab06a1f011d4c09ec108de8bfc54bde57, build: 2.2.1.0, configuration: Release [TFS 2015.2]

[, PID 6636, TID 7692, 2017/08/28 17:05:50.437] TFSAggregator: [Information] Configuration loaded successfully from 'C:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.policies'

[, PID 6636, TID 7692, 2017/08/28 17:05:50.446] TFSAggregator: [Verbose]     Connecting to http://localhost:8080/tfs/DefaultCollection/ as tfsserviceprod

[, PID 6636, TID 7692, 2017/08/28 17:05:51.051] TFSAggregator: [Critical]    Exception encountered processing notification: Error HRESULT E_FAIL has been returned from a call to a COM component. 
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.DataStoreNative64.BeginDataStoreInit(IntPtr handle, String defaultCachePath, String instanceId, Int32 cacheVersion)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.Datastore.BeginDataStoreInit(String defaultCachePath, String instanceId, Int32 cacheVersion)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.InitializeInternal()
   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollection.InitializeTeamFoundationObject(String fullName, Object instance)
   at Microsoft.TeamFoundation.Client.TfsConnection.CreateServiceInstance(Assembly assembly, String fullName)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService(Type serviceType)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService[T]()
   at Aggregator.Core.Facade.WorkItemRepository..ctor(IRuntimeContext context) in D:\a\1\s\Aggregator.Core\Facade\WorkItemRepository.cs:line 44
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(IRuntimeContext runtimeContext) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 67
   at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in D:\a\1\s\Aggregator.Core\Context\RuntimeContext.cs:line 219
   at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in D:\a\1\s\Aggregator.Core\Context\RuntimeContext.cs:line 233
   at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in D:\a\1\s\Aggregator.Core\EventProcessor.cs:line 40
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84
```
I just realized that TFS Aggregator traces version _TFS 2015.2_, although the version of TFS is 2015.3 (14.102.25423.0)
`[, PID 6636, TID 7692, 2017/08/28 17:05:50.390] TFSAggregator: [Information] Aggregator.Core started, version: 2.2.1+Branch.master.Sha.5fd14faab06a1f011d4c09ec108de8bfc54bde57, build: 2.2.1.0, configuration: Release [TFS 2015.2]`

Can this be related to the cause?

**Comment by jessehouwing** [comment]
Write permissions in the tfs/vs programdata folder and the temp directory
to store the process template cache?

**Comment by jessehouwing** [comment]
Does the commandline work when running under the same user?

**Comment by manne** [comment]
the service user has got read, write, and execute right for
- C:\Users\tfsserviceprod\AppData\Local\Microsoft\Team Foundation
- C:\ProgramData\Microsoft\Team Foundation
Are these the folders you mentioned?

The command line does work with the user tfsserviceprod

**Comment by giuliov** [comment]
There is no specific build for 2015 Update 3 as there where no breaking changes; in other words `Release [TFS 2015.2]` is ok.

Jesse also mentioned Temp which means `C:\Users\tfsserviceprod\AppData\Local\Temp`, check also 
`C:\Users\[User]\AppData\Local\Microsoft\Team Foundation\6.0\Cache` (not sure about the 6.0).
You should clear this folder content so there are no leftovers.

His hypothesis that the error cause is lack of permission is sound (try search `DataStoreNative64.BeginDataStoreInit E_FAIL`): the staging machine is hardened like production? What file systems permissions (and groups) has `tfsservicetest` compared to `tfsserviceprod`?

BTW if `tfsserviceprod` had no TFS permission, you would see a managed error; your issue happens at an earlier stage, that is why we suggest looking at the file system.

**Comment by manne** [comment]
I stopped both app pools, cleared the folders, and started the app pools. The behavior is exactly the same.

The accounts are in the same OUs in the AD. Both accounts are in the same local groups.
One difference between the system is, that on the staging system the user is in the group S-1-18-1 [AUTHENTICATION_AUTHORITY_ASSERTED_IDENTITY](https://msdn.microsoft.com/en-us/library/cc980032
). I do not think that this is relevant, because in the temporary web site, the functionality works as expected.

There have not been any manual changes in the local file system permission.
Currently AccessEnum is running on both systems to compare the folder/file permissions.
I will post the result.
