### ISSUE TITLE
TFS Aggregator not working in azure devops server 2019.0.1 onpremise

### ISSUE THREAD

**Issue by HGulec** [tfsaggregator/tfsaggregator#329]
Hi, We upgraded tfs2017 to azure devops 2019.0.1 and tfs aggregator not working in azure devops server 2019.0.1. TFSAggregator log;

TfsAggregator.ServerPlugin        Information       50532    Configuration loaded successfully from 'C:\Program Files\Azure DevOps Server 2019\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.policies'
TfsAggregator.ServerPlugin        Verbose              48988    Connecting to http://xxxxxxxxx:8080/tfs/DefaultCollection/ impersonating WindowsIntegratedAuthenticationToken, running as TFSSERVICE
TfsAggregator.ServerPlugin        Verbose              39412    Built a new Work Item Repository for http://xxxxxxxx:8080/tfs/DefaultCollection/ using a WindowsIntegratedAuthenticationToken
TfsAggregator.ServerPlugin        Verbose              63728    Building Script Engine for C#
TfsAggregator.ServerPlugin        Information       12767    Starting processing on workitem #24043
TfsAggregator.ServerPlugin        Verbose              42629    Policy scope Collections(DefaultCollection) matches DefaultCollection
TfsAggregator.ServerPlugin        Verbose              42629    Policy scope Projects(Burgan_Agile_Test) matches Burgan_Agile_Test
TfsAggregator.ServerPlugin        Critical  47513    Exception encountered processing notification: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) 
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.DataStoreNative64.BrieInvalidateFields(IntPtr handle, Object callback, Int32 fieldId)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.Datastore.BrieInvalidateFields(Object callback, Int32 fieldId)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.ApplyFieldChange(Int32 fieldId, BrieCallBack bc, Int32 recursive)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.ApplyFieldChange(Int32 fieldId, BrieCallBack bc, Int32 recursive)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.ApplyRules(Boolean copyChangedByFromLatest)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem..ctor(WorkItemStore store, Int32 id)
   at Aggregator.Core.Facade.WorkItemRepository.GetWorkItem(Int32 workItemId) in d:\a\1\s\Aggregator.Core\Aggregator.Core\Facade\WorkItemRepository.cs:line 53
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in d:\a\1\s\Aggregator.Core\Aggregator.Core\EventProcessor.cs:line 58
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in d:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 85
TfsAggregator.ServerPlugin        Information       50532    Configuration loaded successfully from 'C:\Program Files\Azure DevOps Server 2019\Application Tier\Web Services\bin\Plugins\TFSAggregator2.ServerPlugin.policies'
TfsAggregator.ServerPlugin        Information       12767    Starting processing on workitem #24044
TfsAggregator.ServerPlugin        Critical  47513    Exception encountered processing notification: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) 
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.DataStoreNative64.BrieInvalidateFields(IntPtr handle, Object callback, Int32 fieldId)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.Datastore.BrieInvalidateFields(Object callback, Int32 fieldId)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.ApplyFieldChange(Int32 fieldId, BrieCallBack bc, Int32 recursive)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.ApplyFieldChange(Int32 fieldId, BrieCallBack bc, Int32 recursive)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.ApplyRules(Boolean copyChangedByFromLatest)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem..ctor(WorkItemStore store, Int32 id)
   at Aggregator.Core.Facade.WorkItemRepository.GetWorkItem(Int32 workItemId) in D:\a\1\s\Aggregator.Core\Aggregator.Core\Facade\WorkItemRepository.cs:line 53
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in D:\a\1\s\Aggregator.Core\Aggregator.Core\EventProcessor.cs:line 58
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 85

**Comment by jessehouwing** [comment]
Never seen that before. Looks like a potential impersonation issue...

https://stackoverflow.com/q/12791207/736079

**Comment by jessehouwing** [comment]
How did you perform the upgrade? Was it in-place, or a fresh install? Did you first uninstall the aggregator prior to updating tfs?

**Comment by HGulec** [comment]
We upgraded azure devops 2019 in new server and after upgrade we install aggregator 2.5.0, 2.5.1RC. Aggregator only working console App. We couldn't find a solution

**Comment by jessehouwing** [comment]
Tip from the Azure DevOps team: 

> You will have to delete following folder and restart your app…
>
>      %USERPROFILE%\AppData\Local\Microsoft\Team Foundation\<version>\Cache

**Comment by jessehouwing** [comment]
And it looks like you need to be on Aggregator 2.5.1b6 at least.

**Comment by joetcochran** [comment]
Using Azure DevOps Server 17.143.28621.4 - Having the same issue (works in console, but not in app - debugview does not log any activity) - do we need Azure DevOps 2019 RC1?

**Comment by jessehouwing** [comment]
Anything in the event viewer?

**Comment by joetcochran** [comment]
I found this, but it doesn't happen every time:
Application Logs - Source: TFSAggregator

Exception encountered processing notification: Please contact your administrator. There was an error contacting the server.
Technical information (for administrator):
  HTTP code 500: Internal Server Error 
Stack Trace:   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.ReadMessage(HttpWebResponse webResponse, WebException webException, Stream responseStream, Boolean& closeResponse)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.ReadResponse(HttpWebResponse webResponse, WebException webException)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequest()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpRequestChannel.Request(TfsMessage message, TimeSpan timeout)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.Invoke(TfsClientOperation operation, Object[] parameters, TimeSpan timeout, Object[]& outputs)
   at Microsoft.TeamFoundation.Framework.Client.LocationWebService.Connect(Int32 connectOptions, Int32 lastChangeId, Int32 features)
   at Microsoft.TeamFoundation.Framework.Client.FrameworkServerDataProvider.Connect(ConnectOptions connectOptions)
   at Aggregator.Core.Facade.WorkItemRepository..ctor(IRuntimeContext context) in d:\a\1\s\Aggregator.Core\Aggregator.Core\Facade\WorkItemRepository.cs:line 45
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(IRuntimeContext runtimeContext) in d:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 68
   at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in d:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 244
   at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in d:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 258
   at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in d:\a\1\s\Aggregator.Core\Aggregator.Core\EventProcessor.cs:line 40
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in d:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 85
    Inner Exception: The remote server returned an error: (500) Internal Server Error. 
Stack Trace:   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequestAndGetResponse(HttpWebRequest webRequest, WebException& webException)

The message resource is present but the message was not found in the message table

**Comment by jessehouwing** [comment]
That 500 error should also be in the logs.. In the IIS logs

**Comment by joetcochran** [comment]
Found the issue - My DebugView filter was off....Had doublequotes around TFSAggregator instead of asterisks. Sorry for the runaround - time to get new glasses or change the resolution on my monitor.
Thanks for the fast replies

**Comment by HGulec** [comment]
Hi,
We can not run tfs aggregator. Our log ;

![image](https://user-images.githubusercontent.com/52749528/63262074-b71fc280-c28d-11e9-8052-8ca62abc2d47.png)

**Comment by HGulec** [comment]
TFS Aggregator only woking in console...... :((

**Comment by giuliov** [comment]
Scroll down the message in EventLog: the interesting part starts after "`The following information was included with the event`". The initial part of the message comes from the event service as haven't registered multi-language messages (because they are not easy to manage in .Net).

**Comment by HGulec** [comment]
The description for Event ID 47513 from source TFSAggregator cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Exception encountered processing notification: TF30063: http://svtsttfsupg01/DefaultCollection/ You are not authorized to access.
Stack Trace:   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.EnsureTokenProvider(HttpWebResponse webResponse)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequest()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpRequestChannel.Request(TfsMessage message, TimeSpan timeout)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.Invoke(TfsClientOperation operation, Object[] parameters, TimeSpan timeout, Object[]& outputs)
   at Microsoft.TeamFoundation.Framework.Client.LocationWebService.Connect(Int32 connectOptions, Int32 lastChangeId, Int32 features)
   at Microsoft.TeamFoundation.Framework.Client.FrameworkServerDataProvider.Connect(ConnectOptions connectOptions)
   at Microsoft.TeamFoundation.Client.TfsConnection.EnsureProviderConnected()
   at Aggregator.Core.Facade.WorkItemRepository..ctor(IRuntimeContext context) in D:\a\1\s\Aggregator.Core\Aggregator.Core\Facade\WorkItemRepository.cs:line 44
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(IRuntimeContext runtimeContext) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 68
   at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in D:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 244
   at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in D:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 258
   at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in D:\a\1\s\Aggregator.Core\Aggregator.Core\EventProcessor.cs:line 40
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 85

the message resource is present but the message is not found in the string/message table

**Comment by giuliov** [comment]
Seems clear that you need to work on permissions
> You are not authorized to access.

A rule code, by default, executes in the security context of the TFS Service Account. See https://tfsaggregator.github.io/admin/troubleshooting/
In alternative, you can use impersonation.
