### ISSUE TITLE
TFS Aggregator stopped working without warning (Could not create SSL/TLS channel)

### ISSUE THREAD

**Issue by IronGem** [tfsaggregator/tfsaggregator#339]
Our instance of the TFS Aggregator plugin recently stopped working.  It had been running without issue for many months before this.  I have reviewed the logs and found the following 

Event Viewer:
```
The description for Event ID 17114 from source TFSAggregator cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Exception encountered processing notification: TF400324: Team Foundation services are not available from server https://<publicServerURL>/tfs/DefaultCollection/.
Technical information (for administrator):
  The request was aborted: Could not create SSL/TLS secure channel. 
Stack Trace:   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.ReadResponse(HttpWebResponse webResponse, WebException webException)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequest()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpRequestChannel.Request(TfsMessage message, TimeSpan timeout)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.Invoke(TfsClientOperation operation, Object[] parameters, TimeSpan timeout, Object[]& outputs)
   at Microsoft.TeamFoundation.Framework.Client.LocationWebService.Connect(Int32 connectOptions, Int32 lastChangeId, Int32 features)
   at Microsoft.TeamFoundation.Framework.Client.FrameworkServerDataProvider.Connect(ConnectOptions connectOptions)
   at Aggregator.Core.Facade.WorkItemRepository..ctor(IRuntimeContext context) in d:\a\1\s\Aggregator.Core\Aggregator.Core\Facade\WorkItemRepository.cs:line 45
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(IRuntimeContext runtimeContext) in d:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 68
   at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in d:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 244
   at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in d:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 258
   at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in d:\a\1\s\Aggregator.Core\Aggregator.Core\EventProcessor.cs:line 40
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in d:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 85
    Inner Exception: The request was aborted: Could not create SSL/TLS secure channel. 
Stack Trace:   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequestAndGetResponse(HttpWebRequest webRequest, WebException& webException)

the message resource is present but the message is not found in the string/message table
```

Debug View:
```[10660] TFSAggregator: [Critical]    Exception encountered processing notification: TF400324: Team Foundation services are not available from server https://<publicServerURL>/tfs/DefaultCollection/. ```

The console app works without issue using the same policy file as the plugin.  I can reach the TFS webpage in Chrome using the Service account.  The site certificate is valid and trusted.  TFS version 2017.3, I was using TFSAggregator 2.4.0, but tried uninstalling and installing the latest 2.5.2 beta 3 after this started.  Still same issue.  No other changes were made to the TFS servers before this started. 

Please let me know if you need any further information.

Thank you,
Jason

**Comment by giuliov** [comment]
I agree that there is a SSL/TLS issue (`Could not create SSL/TLS secure channel` message). It might be that the server was configured ot use TLS 1.3 or so (some Windows updates force new behaviour). I would check the registry keys in `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319` and any recent patch installed. Was the certificate renewed, is it Self-signed?

**Comment by IronGem** [comment]
Giulio,
Thank you for your suggestion.  At first, I was not sure what you meant by checking those regkeys, so I messed with enabling TLS in the HKLM/System/CurrentControlSet/Control/SecurityProviders/SCHANNEL/Protocols Keys and trying to figure out why the secure channel could not be established.  Finally I found this page https://johnlouros.com/blog/enabling-strong-cryptography-for-all-dot-net-applications which, i think, explains where you were trying to direct me.  After adding that dword and rebooting, Aggregator kicked right back on.  I believe this happened when our load balancer, which handles our encryption, was updated to only accept TLS 1.2. 
Thank you, once again, for your help and this amazing tool.

**Comment by giuliov** [comment]
Yes, exactly. I faced similar issues related to TLS 1.2 on .Net 3.5, but I believed that .Net 4.x was immune from this issue. My place to go is https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls but on the spot I could only find some snippets in my code archives.
Happy that it is solved now.
