### ISSUE TITLE
Aggregator 2 HTTP 500 when using impersonation

### ISSUE THREAD

**Issue by vlaquest** [tfsaggregator/tfsaggregator#361]
Hi, we just upgraded our TFS server from 2017 update 3 to  8.170.30910.2 (Azure DevOps Server 2020.0.1) on a test server

So I installed v2.6.1-beta.1 and impersonation does not work for me
<authentication autoImpersonate="true" /> => causes an HTTP 500 error in the event log.

When autoImpersonate is off, it all works on the server.
CLI works as well

When autoImpersonate is true, CLI cannot be used as usual, but server rules crash

HTTP code 500: Internal Server Error 
Stack Trace:   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.ReadMessage(HttpWebResponse webResponse, WebException webException, Stream responseStream, Boolean& closeResponse)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.ReadResponse(HttpWebResponse webResponse, WebException webException)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequest()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpRequestChannel.Request(TfsMessage message, TimeSpan timeout)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.Invoke(TfsClientOperation operation, Object[] parameters, TimeSpan timeout, Object[]& outputs)
   at Microsoft.TeamFoundation.Framework.Client.LocationWebService.Connect(Int32 connectOptions, Int32 lastChangeId, Int32 features)
   at Microsoft.TeamFoundation.Framework.Client.FrameworkServerDataProvider.Connect(ConnectOptions connectOptions)
   at Aggregator.Core.Facade.WorkItemRepository..ctor(IRuntimeContext context) in D:\a\1\s\Aggregator.Core\Aggregator.Core\Facade\WorkItemRepository.cs:line 45
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(IRuntimeContext runtimeContext) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 68
   at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in D:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 244
   at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in D:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 258
   at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in D:\a\1\s\Aggregator.Core\Aggregator.Core\EventProcessor.cs:line 40
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 85
    Inner Exception: The remote server returned an error: (500) Internal Server Error. 
Stack Trace:   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequestAndGetResponse(HttpWebRequest webRequest, WebException& webException)

I have not tried to revert to an older version...

**Comment by jessehouwing** [comment]
If you check the server event logs, are is there a asp.net error log from the server showing more details if the exception causing the error?

Have you tried the documented debugging steps?

Without more details, I can't do much.

**Comment by vlaquest** [comment]
Hi Jesse,
Thanks for your reactivity,
This was the only exception I had in the event viewer, no other ASP.NET message.

But the problem is solved, it was completely my fault => I forgot to give the "Make requests on behalf of others" permission to the service account. Now impersonation works well.

Thanks again and sorry for this non-issue. I just feared there was an incompatibility with this version.
best regards,
Vincent

**Comment by jessehouwing** [comment]
Thanks for the quick feedback. Enjoy using it!
