### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by KocamanFaruk** [tfsaggregator/tfsaggregator#400]
Hello,

Is there going to be new version soon? We want to upgrade our Azure Devops Server to 2022.2 RTW but "tfsaggregator" does not support.

Please inform us.

Thank you,

**Comment by jessehouwing** [comment]
Hey Faruk,

Thanks for inquiring, but, please note that this project is in **deprecated** state. If people have needs of the project, they can provide a pull request and I'll happily merge it and release a new version, but there is no work or release planned beyond this point by the team that maintained the TFS Aggregator plugin.

We've been offering the aggregator-cli project for several years now as an alternative.
https://marketplace.visualstudio.com/items?itemName=tfsaggregatorteam.aggregator-cli

If you have a need to run this plugin version, please help us, and possibly others, by submitting a pull request that contains the required changes and test that version on our behalf.

Jesse Houwing

**Comment by KocamanFaruk** [comment]
Created a pull request, thank you.

**Comment by KocamanFaruk** [comment]
Deleted the branch and PR is automatically closed so i will ask from here.

Thank you for the clarification btw but i have another question if you dont mind.

If i would want to install this version which is supported in latest beta (2022.1 RTW | 19.225.34309.2) Can i install its patches like 2022.1 Patch 1 or Patch 2 or is it really dependent Semantic Version number included in product.wxs file? Because 2022.1 Patch 1 (19.225.34328.1) version number not included in Product.wxs file.

https://github.com/FokkoVeegens/AzureDevOpsServerVersions/blob/main/README.md#2022

**Comment by jessehouwing** [comment]
The installer is quite picky. Azure DevOps itself generally isn't that picky, it's why we can install the same binaries for many multiple versions, but sometimes the APIs change and the binaries break. That's what the installer technology is trying to solve. Our build process spits out some 10 differently compiled binaries to deal with the incompatibilities introduced since we started out.

Your server will likely survive an upgrade, though the Azure DevOps Server installer may throw away the plugin binaries. If you copy them back to the right place, in many cases, the plugin will load without issues. If it fails to load, there is usually some incompatibility that needs to be solved using recompilation for tat specific Azure DevOps Server version.

Since I haven't tested 2022.2 yet, I don't know if there are any binary issues. Hence I hope someone picks up the challenge and submits a verified pull request.

**Comment by jessehouwing** [comment]
Things that will break the integration:

 * New major versions of the Server Object Model
 * New major versions of the client object model
 * New dependencies or types moved to a different assembly
 * Contract changes in any of the types we depend on
 * The installation path in the registry of the plugin changes

Every time the binaries changed too much or the server's installation path changes, we had to create a new targets file to pull in the right references:
https://github.com/tfsaggregator/tfsaggregator/tree/develop/References

Every time code changed we have introduced a few compiler directives to IF/ELSE our way out of those issues:
https://github.com/search?q=repo%3Atfsaggregator%2Ftfsaggregator%20%23if%20path%3A.cs&type=code

To be sure we don't drop an incompatible assembly in a production server's environment, the installer has a list of officially supported exact versions that instruct the installer where to drop exactly what version of the plugin. 

Unfortunately the breaking changes haven't always been as predictable. Sometimes breaking between even minor versions of Azure DevOps Server, sometimes staying the same even across major versions.

**Comment by KocamanFaruk** [comment]
Hello,

I try to compile the solution in my local server. Installed WiX and xUnit extension but as you can see in the screenshot, there are some references error which it can not find. In your "LOCAL BUILD" note "TFS is not required to build nor debugging", TFS is not installed on the server. So, can you help me about this issue?

Thank you.

![image](https://github.com/user-attachments/assets/45d66bb8-69c4-4206-9500-8e68c2087bde)

**Comment by jessehouwing** [comment]
You must install Azure DevOps Server 2022 on the machine (doesn't have to
be configured), just run the installer and then close the configuration
wizard.

Microsoft doesn't distribute these binaries and license prevents us from
distributing them.

**Comment by KocamanFaruk** [comment]
Okay, i installed VS2022 with extensions on Azure Devops Server which is version 19.205.33122.1 (Azure DevOps Server 2022).  Still it does not load the references, should i put them to myself to specific folder?

![image](https://github.com/user-attachments/assets/f2b3e869-5551-4ef0-8a21-85d8e54d0083)



Edit: Sorry, i forgot to change solution configuration to Debug-2022.1. Now it is compiling.

**Comment by jessehouwing** [comment]
Looks like you've selected the TFT2013 build configuration for the
solution. Change that to the latest 2022.

**Comment by KocamanFaruk** [comment]
Thank you for the help.

Last question, after compiling, is it enough to put these 4 files in "C:\Program Files\Azure DevOps Server 2022\Application Tier\Web Services\bin\Plugins" folder?

![image](https://github.com/user-attachments/assets/53093518-2712-4a52-9033-421a6ec9a85f)

**Comment by KocamanFaruk** [comment]
Okay, changed the dll files in this folder "C:\Program Files\Azure DevOps Server 2022\Application Tier\Web Services\bin\Plugins", when i execute "C:\Program Files\TFS Aggregator\bin\TFSAggregator2.ConsoleApp.exe" i get this error;

TFSAggregator2.ConsoleApp 1.0.0+cb877d8c99b750945319168e7e88359084ddb7d6

Build: 2.7.1, Configuration: Release-2022 [TFS 2022]
Copyright (c) TFS Aggregator Team 2015-2023
Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

Edit: Forgot the put it in here > C:\Program Files\TFS Aggregator\bin. Now it is working.

**Comment by devAlex-sys** [comment]
We ran into the same problem. With Azure Dev Ops Server 2022.2 Microsoft removed required Dlls from the folder "Azure DevOps Server 2022\Application Tier\Web Services\bin"

```
Exception encountered processing notification: Could not load file or assembly 'Microsoft.TeamFoundation.WorkItemTracking.Client, Version=19.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. 
Stack Trace:   at Aggregator.Core.Facade.WorkItemRepository..ctor(IRuntimeContext context)
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(IRuntimeContext runtimeContext) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 68
   at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in D:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 244
   at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in D:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 258
   at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in D:\a\1\s\Aggregator.Core\Aggregator.Core\EventProcessor.cs:line 40
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 85
```

**Workaround:**
You can copy the missing Dlls from the folder "Azure DevOps Server 2022\Tools"

> Microsoft.TeamFoundation.WorkItemTracking.Client.dll
> Microsoft.TeamFoundation.WorkItemTracking.Client.DataStoreLoader.dll
> Microsoft.WITDataStore64.dll

**Comment by jasondavidcamp** [comment]
We are also running into the same problem with another custom TFS Plugin. Since there isn't an NuGet package for Microsoft.TeamFoundationServer.ExtendedClient 19.235.35102.1 (matches Azure DevOps Server 2022 update 2) we don't know what package references to use without copying the dlls explicitly. Is there an easy way to tag a Microsoft resource here or should I just open a Microsoft case?

**Comment by jasondavidcamp** [comment]
I just opened a Microsoft case on this for them to publish NuGet packages for Microsoft.TeamFoundationServer.Client and Microsoft.TeamFoundationServer.ExtendedClient for version 19.235.35102.1.

**Comment by jessehouwing** [comment]
We can probably add a static reference loader function to probe the other directory. There's already something similar here:

https://github.com/jessehouwing/azure-pipelines-gate-condition-editor/blob/main/ServerTaskExpressionTester/Program.cs#L14-L81

Doing that from a static constructor may do the trick. 

Otherwise you'll have to do some serious juggling to get the installer to work.

**Comment by jessehouwing** [comment]
Editing the config file to add a probing path in the webservice's `web.config` may also work:

```xml
<configuration>  
   <runtime>  
      <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">  
         <probing privatePath="C:\Program Files\Azure DevOps Server 2022\Tools"/>  
      </assemblyBinding>  
   </runtime>  
</configuration>  
```

**Not tested!**

**Comment by jasondavidcamp** [comment]
> We ran into the same problem. With Azure Dev Ops Server 2022.2 Microsoft removed required Dlls from the folder "Azure DevOps Server 2022\Application Tier\Web Services\bin"
> 
> ```
> Exception encountered processing notification: Could not load file or assembly 'Microsoft.TeamFoundation.WorkItemTracking.Client, Version=19.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. 
> Stack Trace:   at Aggregator.Core.Facade.WorkItemRepository..ctor(IRuntimeContext context)
>    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(IRuntimeContext runtimeContext) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 68
>    at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in D:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 244
>    at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in D:\a\1\s\Aggregator.Core\Aggregator.Core\Context\RuntimeContext.cs:line 258
>    at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in D:\a\1\s\Aggregator.Core\Aggregator.Core\EventProcessor.cs:line 40
>    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in D:\a\1\s\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 85
> ```
> 
> **Workaround:** You can copy the missing Dlls from the folder "Azure DevOps Server 2022\Tools"
> 
> > Microsoft.TeamFoundation.WorkItemTracking.Client.dll
> > Microsoft.TeamFoundation.WorkItemTracking.Client.DataStoreLoader.dll
> > Microsoft.WITDataStore64.dll

This workaround does work for us with the TFSAggregator.

**Comment by jasondavidcamp** [comment]
It looks to me as if Microsoft changed the Microsoft.TeamFoundation.WorkItemTracking.Client.dll to Microsoft.TeamFoundation.WorkItemTracking.ClientSlim.dll in 2022 update 2. (In \Program Files\Azure DevOps Server 2022\Application Tier\Web Services\bin folder) If we had a NuGet package that included the "ClientSlim" version, we could probably use it instead of just copying DLLs from the tools area.

**Comment by jessehouwing** [comment]
That might be something a new compile target would solve as well, assuming the methods we rely on are still there...

**Comment by jasondavidcamp** [comment]
We have been getting warnings for some time that Microsoft deprecated the Work Item Tracking OM
https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/wit-client-om-deprecation?view=azure-devops&viewFallbackFrom=azure-devops-2022

**Comment by jessehouwing** [comment]
> We have been getting warnings for some time that Microsoft deprecated the Work Item Tracking OM https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/wit-client-om-deprecation?view=azure-devops&viewFallbackFrom=azure-devops-2022

It's why this project is also officially deprecated.

**Comment by jasondavidcamp** [comment]
Understood. We see the writing on the wall that Azure DevOps Server is on life support and are working to migrate away from the product. It's been a great 20 years though!
