### ISSUE TITLE
How to get Related work items?

### ISSUE THREAD

**Issue by Wylde44** [tfsaggregator/tfsaggregator#95]
Hi,
I'm trying to get related work item 
var related = self.FollowingLinks("Related").WhereTypeIs("Task");
or
var related = self.FollowingLinks("System.LinkTypes.Related").WhereTypeIs("Task");
and aggregator fails with the following:

Exception encountered processing notification: Object reference not set to an instance of an object. 
Stack Trace:   at RESERVED.Script_ScriptName.RunScript(IWorkItemExposed self, IWorkItemRepositoryExposed store, IRuleLogger logger) in c:\Users\user\AppData\Local\Temp\mv23520m.1.cs:line 20
   at Aggregator.Core.Script.DotNetScriptEngine`1.RunScript(Assembly assembly, String scriptName, IWorkItem self, IWorkItemRepository store)
   at Aggregator.Core.Script.DotNetScriptEngine`1.Run(String scriptName, IWorkItem workItem, IWorkItemRepository store)
   at Aggregator.Core.EventProcessor.ApplyRules(IWorkItem workItem, IEnumerable`1 rules)
   at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification)
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(TeamFoundationRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties)

But it works fine with "System.LinkTypes.Hierarchy-Reverse"

Where am i wrong?

TfsAggregator 2.0.114
Tfs2013 upd 5
Thanks in advance!

**Comment by Wylde44** [comment]
Solved it! In my case only "System.LinkTypes.Related-Forward" works.

**Comment by giuliov** [comment]
Nice to hear this. You can also update to build 128 which we consider 2.0 RTM (no big features, mostly fixes here and there).
